### ISSUE TITLE
Not connect with Smart22. Error start. Delegated Dmitryi Pachkovskyi

### ISSUE THREAD

**Issue by AquaDiscote** [SmartSystemLtd/planningRepo#289]
1. Обнаружили нехватку памяти ПЗУ VDI01, VDI02
- [x] Выяснить у Пачковского как он решил проблему

**Comment by it48dmt** [comment]
Решение: была нарушена репликация в результате нехватки места ПЗУ . В дальнейшем была оптимизирована схема расположения виртуальных машин, на данном этапе проблема пространства решена.
